govCMS/scaffold-tooling

.gitlab-ci-main.yml

Normally linting is done by bringing up the test container. This is a "best principle" method that ensures everything can be run in a standard environment, but it's also a bit silly, because linting might take 5-10 minutes on a good day.
This change allows linting to be optionally run outside the container. This may take as little as 1 minute.
It can be enabled in a project's .gitlab-ci-inputs.yml with:
```
.variables:
GOVCMS_FAST_LINTING: "TRUE"
```
When creating `govCMS/scaffold-tooling` I tried to stick to principles of running everything in docker, but actually I think this is overkill for linting. So I would argue that there shouldn't be an option to switch it on or off, just use the fast option.

Much faster linting

---

.circleci/config.yml
.circleci/phpcs.sh
.circleci/shellcheck.sh
composer.json
drupal/settings/all.settings.php
drupal/settings/development.settings.php
drupal/settings/lagoon.settings.php
drupal/settings/production.settings.php
scripts/govcms-deploy
scripts/tests/govcms-audit
scripts/tests/govcms-behat
scripts/tests/govcms-lint
scripts/tests/govcms-lint-distro
scripts/tests/govcms-phpunit
scripts/tests/govcms-vet

Large PR as too many files had their coding standards violated.
No logic was touched - only fixed the part were linters were showing errors.
**Why do we need to do this cleanup now and not later?**
Because this cleanup enables future coding standards checks. We want all the future changes to be done properly, so we do not have to come back to fixing (and potentially breaking) them.

Enabled coding standards checking in CI and fixed coding standards.

---

scripts/govcms-deploy
tests/bats/_helpers.bash
tests/bats/_helpers_govcms.bash
tests/bats/govcms-deploy.bats

- Added bats tests for `govcms-deploy` script with different input parameters:
```
1. Defaults, no config
2. Defaults, no config, not installed
3. Production, no config
4. Production, default and dev config
5. Production, no config, retain config
6. Production, default and dev config, retain config
7. Production, default and dev config, import content
8. Production, no config, not installed
9. Development, no config
10. Development, default and dev config
11. Development, no config, retain config
12. Development, default and dev config, retain config
13. Development, default and dev config, import content
14. Development, no config, not installed
15. Local, no config
16. Local, default and dev config
17. Local, no config, retain config
18. Local, default and dev config, retain config
19. …
```

Added tests for govcms-deploy.

---

drupal/settings/lagoon.settings.php
scripts/deploy/govcms-db-sync
scripts/govcms-deploy
tests/bats/deploy/govcms-db-sync.bats
tests/bats/deploy/govcms-db-update.bats
tests/bats/govcms-deploy.bats
tests/bats/settings/general.bats

- Added changes from https://github.com/govCMS/govcms8lagoon/pull/83
- Added tests for `govcms-deploy`
- Added tests for chunked deploy script `scripts/deploy/govcms-db-sync`.
- Fixed `scripts/deploy/govcms-db-sync` drush commands to use Drush 9 aliases (we are already using them in `govcms-deploy`). This is to remove ambiguity in supported Drush versions.
Note that there is no support for `sql-dump` added as Drush 9 does not support `--source-database` key. See https://github.com/drush-ops/drush/issues/4274
Changes in commits are self-contained, so can be reviewed per commit to make it easy to understand.

[GOVCMSD8-556] Add support for DB replica when performing DB synchronisation.

---

scripts/deploy/govcms-db-sync
scripts/govcms-deploy
tests/bats/deploy/govcms-db-sync.bats
tests/bats/govcms-deploy.bats

- Drush 9 does not provide the option for --source-database option for the syql:sync command.
```
$ drush sql:sync @govcms.prod @self --source-database=read -y
The "--source-database" option does not exist.  
```

Remove --source-database from sync task.

---

drupal/settings/all.settings.php
drupal/settings/development.settings.php
drupal/settings/lagoon.settings.php
drupal/settings/production.settings.php
tests/bats/govcms-vet.bats

`govcms_settings` is not defined, which causes bootstrap issues.
Namely in the (unreleased) `2.0.0` PaaS scaffold `development.services.yml` cannot be loaded, and fails with
```
You have requested a non-existent service "cache.backend.null". Did you mean one of these: "cache.backend.apcu", "cache.backend.memory", "cache.backend.php"?
```
This is because includes silently fail.

Define govcms_settings.

---

scripts/deploy/govcms-enable_modules
tests/bats/integration.bats

Drush `pm:enable` expects a [comma-separated list of modules](https://drushcommands.com/drush-9x/pm/pm:enable/).

Ensure module list is comma separated.

---

composer.json
tests/bats/govcms-vet.bats
tests/bats/integration.bats

Update `drupal/fast_404` since the 1.x branch is unsupported.

[GOVCMSD8-666] Update drupal/fast_404

---

composer.json

See #59 and #58 
Removed console here, obviously that may not fly
ClamAV and Fast 404 are going to be watch and wait for D9 releases.

Loosen constraints in an attempt to move to D9

---

.gitlab-ci-main.yml

This code change removes any local overrides (prefixed with ###) in docker-compose.yml. See: https://github.com/govCMS/govcms8-scaffold-paas/pull/64

[GOVCMS-5020] Remove local overrides in CI.

---

scripts/deploy/govcms-update_site_alias

This is a stopgap measure; with the scaffold update to 1.2.0 the `mkdir -p` was removed and it has not been added to a script in scaffold-tooling. This is a hotfix to restore functionality while a more permanent fix is added in an upcoming release as scaffold updates take at minimum 19 hours to complete.
- Create a new deploy script `govcms-prepare` that can house any operations that need to be actioned prior to an environment being created
- Update the scaffold to execute the prepare script
- Rollout the update to the fleet.

Ensure directories are available.

---

drupal/modules/lagoon/govcms_lagoon/govcms_lagoon.info.yml
drupal/modules/lagoon/lagoon_search/lagoon_search.info.yml

Noting we are still waiting on a 9.x release for clamav/fast_404

Added core_version_requirement key.

---

composer.json

The chosen library should be shipped/bundled with the distribution rather than in tooling.

Removed chosen_lib from tooling.

---

drupal/settings/production.settings.php

- Adds the `GOVCMS_FILE_TEMP_MAX_AGE` environment variable to allow support agents to enable temporary file GC.

Enable gc override.

---

drupal/settings/all.settings.php

- Allows client max timeouts to be controlled per project.
Ref: https://github.com/govCMS/govcms8lagoon/pull/182

[GOVCMSD8-765]: Add client timeout configuration.

---

drupal/settings/lagoon.settings.php

`REDIS_PORT` is incorrectly set in Lagoon/Openshift to a full TCP address of the redis host. This causes an invalid port when attempting a redis connection so this will fail and default the site to use a null backend.
https://github.com/govCMS/govcms8lagoon/blob/develop/.docker/images/govcms8/settings/settings.php#L175

Change REDIS_PORT to REDIS_SERVICE_PORT.

---

scripts/deploy/govcms-db-update
tests/bats/deploy/govcms-db-update.bats

```
GovCMS Deploy :: Update Database
[info]: Detected Drupal 9 codebase.
[info]: Detected Drupal 8 core database schema.
[info]: Running cache-rebuild prior to database update.
[success] Cache rebuild complete.
```
8.x => 9.x upgrade pathway requires a cache-rebuild before database updates.
Also adds a more generic env var `GOVCMS_CACHE_REBUILD_PRE_UPDB` for future use

Ensure cache-rebuild for first-time 9.x upgrade.

---

drupal/settings/lagoon.settings.php
scripts/deploy/govcms-db-sync
scripts/govcms-deploy

* Prevents drush attempting to import a gz file via sqlc
* Ensures database sync always happens on canary environments

Moved to more controlled dump and sync for non-prod environments.

---

scripts/deploy/govcms-db-update
scripts/govcms-deploy

Fixes fairly widespread `the theme * does not exist` issues during build.

Run cache clear before updb.

---

drupal/settings/settings.php

Moved default `settings.php` to scaffold-tooling rather than tracking files in downstream repos.
This can be copied into place with the standard scaffolding setup.

[GOVCMS-5036] Added entrypoint settings.php.

---

drupal/settings/all.settings.php
drupal/settings/development.settings.php
drupal/settings/lagoon.settings.php
drupal/settings/production.settings.php
tests/bats/settings/edge.bats
tests/bats/settings/environments.bats
tests/bats/settings/general.bats
tests/bats/settings/performance.bats
tests/bats/settings/security.bats
tests/drupal-settings-to-json.php

- Removed legacy solr configuration (included in all.settings.php anyway)
- Added missing environment indicator settings.
- Moved from deprecated drupal_installation_attempted() method.
This PR aligns scaffold-tooling settings to those found in the govcms8lagoon image. Once merged we can remove all settings managed separately in downstream consumers (e.g: https://github.com/govCMS/govcms8lagoon/pull/197)

[GOVCMS-5033] Removed legacy solr configuration.

---

drupal/settings/dev-mode.settings.php
drupal/settings/development.settings.php
drupal/settings/settings.php

Ensures that non-production settings and `DEV_MODE` overrides are separated.

Split non-production settigs vs dev_mode.

---

composer.json
tests/bats/settings/environments.bats

`parallel-lint` is used by the `govcms-lint` script but not explicitly defined as a tooling dependency

Define explicit parallel-lint dependency

---

scripts/govcms-behat

Aligns with https://github.com/govCMS/govcms8lagoon/blob/develop/.docker/scripts/behat.
Behat binary lives in `/app/tests` vendor folder on default test images.

Updated behat binary path.

---

scripts/validate/govcms-validate-platform-yml
tests/bats/settings/environments.bats

1. Adds docker-compose.yml file to govcms-validate-platform script. 
2. Fixes environments.bats tests after the recent change in #99.
**NOTE**
The docker-compose.yml file in govcms8-scaffold AND the new scaffold has invalid YAML syntax and there are two PRs to fix this: [govcms8-scaffold](https://github.com/govCMS/govcms8-scaffold/pull/55) and [new scaffold](https://github.com/govCMS/scaffold/pull/9). They need to be merged after that PR.

[GOVCMSD8-709] Lint docker compose.yml

---

.gitlab-ci-main.yml

GitLab CI artifacts are currently not captured due to misconfigured paths in CI config.
As per Behat config in the files below, the path is `%paths.base%/screenshots` rather than ` %paths.base%/features/screenshots`:
https://github.com/govCMS/GovCMS8/blob/1.x/tests/behat/behat.yml#L44
https://github.com/govCMS/scaffold/blob/develop/tests/behat/behat.yml#L44
Passing build with artifacts: https://projects.govcms.gov.au/nsw-ipart/ipart/-/jobs/633569

Fixed the path of Behat screenshots in CI.
